"use client";
import {useEffect,useState} from "react";
const modules=[
["01","AI Website Development","利用 AI 规划、设计及开发现代网站。"],["02","AI Prompt for Web","掌握精准指令，开发、修改与优化网站。"],["03","Web Design & UI/UX","Layout、Typography、Colour 与 Responsive Design。"],["04","AI Coding","理解并控制 AI 生成的 HTML、CSS 与 JavaScript。"],["05","Modern Web Tools","理解 WordPress 与 AI 开发的应用场景。"],["06","Domain / Deployment","把网站从电脑真正发布到互联网。"],["07","Freelancer Business","报价、Proposal、沟通、收款与项目管理。"],["08","Real Project Practice","完成真正可以展示及交付的网站项目。"]];
const steps=[["LEARN","学习 AI、设计及网站开发基础。"],["BUILD","利用 AI 开发真实网站。"],["TEST","测试多设备、效能与用户体验。"],["LAUNCH","连接 Domain 与 Hosting 正式上线。"],["SELL","把能力包装成服务，接触真实客户。"]];
const faqs=[["需要懂 Coding 吗？","不需要拥有 Programming Background。课程会教你理解网站结构，并利用 AI 协助开发及修改网站。"],["课程是不是只教 AI？","不是。课程结合 AI Website Development、Web Design、网站上线、Freelancer Business 与真实项目经验。"],["学完可以接 Freelance Project 吗？","课程目标之一是让学员掌握完整 Freelancer Workflow；实际成果取决于个人能力、作品、执行力及市场情况。"],["课程费用是多少？","原价 RM3,800，并提供标准付款、分期付款及 RyanKey 粉丝优惠方案。"]];
type Plan="Standard Payment"|"Instalment Payment"|"RyanKey Fans Special";
export default function Home(){
const[menu,setMenu]=useState(false),[modal,setModal]=useState(false),[sent,setSent]=useState(false);const[plan,setPlan]=useState<Plan>("RyanKey Fans Special"),[error,setError]=useState("");
useEffect(()=>{const o=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("seen")),{threshold:.12});document.querySelectorAll(".reveal").forEach(e=>o.observe(e));return()=>o.disconnect()},[]);
const open=(p:Plan="RyanKey Fans Special")=>{setPlan(p);setModal(true);setSent(false);setError("")};
const submit=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget),phone=String(d.get("phone")||"").replace(/\D/g,"");if(phone.length<9){setError("WhatsApp 电话必须至少包含 9 个数字。");return}const m=`Hi Ryan，我对 2026 Freelancer Course｜AI Website Development 有兴趣。\n\nName: ${d.get("name")}\nPayment Plan: ${d.get("plan")}\nPhone: ${d.get("phone")}\nEmail: ${d.get("email")}\nOccupation: ${d.get("occupation")}`;setSent(true);setTimeout(()=>window.open(`https://wa.me/60127740280?text=${encodeURIComponent(m)}`,"_blank","noopener,noreferrer"),400)};
return <><header className="nav"><a className="brand" href="#home">RK<span>®</span> / COURSE 26</a><button className="hamb" onClick={()=>setMenu(!menu)} aria-label="打开菜单">MENU</button><nav className={menu?"open":""} onClick={()=>setMenu(false)}><a href="#why">Why AI</a><a href="#course">Course</a><a href="#learn">What You&apos;ll Learn</a><a href="#freelancer">Freelancer</a><a href="#mentor">RyanKey</a><a href="#fees">Fees</a><a href="#faq">FAQ</a></nav><button className="navCta" onClick={()=>open()}>JOIN COURSE ↗</button></header>
<main id="home"><section className="hero"><div className="heroGrid"/><div className="orb one"/><div className="orb two"/><div className="eyebrow"><span>LIVE / OCT 2026</span><span>KUALA LUMPUR</span></div><h1><span>2026</span> FREELANCER<br/>COURSE</h1><div className="heroBottom"><div><p className="cnTitle">更注重 <mark>AI 网站开发</mark></p><p className="enTitle">FROM WEB DESIGNER TO<br/>AI WEBSITE DEVELOPER</p></div><div className="intro"><p>结合 AI、设计、开发思维与 Freelancer 商业能力，把一个 Idea 发展成真正可以上线及交付的网站。</p><div className="actions"><a className="primary" href="#course">查看课程内容 ↓</a><button className="secondary" onClick={()=>open()}>立即报名 ↗</button></div></div></div><div className="ticker"><span>AI WEBSITE DEVELOPMENT</span><b>✦</b><span>REAL PROJECT</span><b>✦</b><span>FREELANCER BUSINESS</span><b>✦</b><span>BUILD YOUR FUTURE</span></div></section>
<section className="why section" id="why"><p className="label">01 / THE SHIFT</p><div className="whyGrid reveal"><h2>网站设计<br/>正在改变<span>。</span></h2><div className="whyCopy"><p className="lead">过去，Web Designer 学习设计、WordPress、UI 和网站制作。<br/><strong>现在，AI 已经改变整个开发流程。</strong></p><div className="skillList">{["使用 AI 开发网站","把 Idea 转化成 Website","设计 UI / UX 与 Responsive Layout","处理 Domain / Hosting / 上线","面对客户、报价与修改需求","把技术变成收费服务"].map((x,i)=><div key={x}><span>0{i+1}</span>{x}</div>)}</div></div></div><blockquote className="reveal">这不只是一堂 Web Design Course，<br/>而是一套 <em>Freelancer + AI Website Development</em> 的实战训练。</blockquote></section>
<section className="course section" id="course"><div className="sectionHead"><div><p className="label">02 / COURSE CORE</p><h2>你将真正<br/>学会什么？</h2></div><p>8 个核心模块。<br/>从想法，到上线，到收费。</p></div><div className="bento" id="learn">{modules.map((m,i)=><article className={`module reveal m${i+1}`} key={m[0]}><span>{m[0]}</span><div className="moduleIcon">{i%3===0?"✣":i%3===1?"⌘":"↗"}</div><h3>{m[1]}</h3><p>{m[2]}</p></article>)}</div></section>
<section className="process section" id="freelancer"><p className="label">03 / THE WORKFLOW</p><h2 className="reveal">不是看完。<br/><mark>是做出来。</mark></h2><div className="steps">{steps.map((s,i)=><article className="reveal" key={s[0]}><span>0{i+1}</span><h3>{s[0]}</h3><p>{s[1]}</p></article>)}</div></section>
<section className="audience section"><div className="audienceTitle"><p className="label">04 / WHO IS THIS FOR?</p><h2>适合想<br/>改变方向的你。</h2><div className="noCode">NO CODE<br/><strong>BACKGROUND</strong><br/>REQUIRED ↗</div></div><div className="tags reveal">{["Future Freelancer","Web Designer","Graphic Designer","Digital Marketer","Content Creator","College Student","Career Switcher","WordPress User","Non-Coder","Business Owner"].map(t=><span key={t}>{t}</span>)}</div><p className="audienceNote">重点不是训练传统 Programmer，<br/>而是训练懂得利用 AI 完成网站项目的<strong>新一代 Freelancer。</strong></p></section>
<section className="mentor section" id="mentor"><div className="mentorTop"><p className="label">05 / MEET YOUR MENTOR</p><a href="https://ryankey.com.my/" target="_blank" rel="noreferrer">OFFICIAL WEBSITE ↗</a></div><div className="mentorHero reveal"><div className="mentorName"><span>YOUR MENTOR</span><h2>RYAN<br/>KEY<span>.</span></h2></div><div className="mentorIntro"><p className="role">Chief Web Design<br/>& Branding Advisor</p><p>拥有超过 <strong>20 年网页设计与品牌策略经验</strong>，长期协助中小型企业建立专业网站、提升品牌价值，并结合 Google SEO、数码营销及 AI Ready 架构推动业务成长。</p><div className="mentorTags"><span>WEB DESIGNER</span><span>DIGITAL MARKETING TRAINER</span><span>AI PERSONAL BRANDING CONSULTANT</span></div><a className="mentorLink" href="https://ryankey.com.my/" target="_blank" rel="noreferrer">了解更多 RYAN KEY 资料 ↗</a></div></div><div className="mentorStats reveal"><article><strong>20+</strong><span>YEARS OF<br/>REAL EXPERIENCE</span></article><article><strong>SME</strong><span>DIGITAL BUSINESS<br/>SOLUTIONS</span></article><article><strong>AI</strong><span>READY WEBSITE<br/>DEVELOPMENT</span></article></div><div className="mentorPillars"><article className="reveal"><span>01 / SOLUTIONS</span><h3>企业数码解决方案</h3><p>从品牌定位、网站策略、Google SEO 到 AI Ready 架构，为中小型企业规划可持续成长的数码系统，让网站成为真正的业务资产。</p></article><article className="reveal"><span>02 / GROWTH</span><h3>教学与持续成长</h3><p>结合超过 20 年实战经验，分享网页设计、品牌策略、数码营销与 AI 应用知识，推动新一代创意人才成长。</p></article><article className="reveal"><span>03 / CONNECTION</span><h3>商业合作与资源连接</h3><p>连接企业、Freelancer、教育机构与专业伙伴，整合设计、技术、营销及商业资源，创造长期合作价值。</p></article></div><blockquote className="mentorQuote reveal">“我不只是教你怎样做网站，<br/>而是把真实市场经验带进课堂。”</blockquote></section>
<section className="pricing section" id="fees"><div className="sectionHead"><div><p className="label">05 / INVESTMENT</p><h2>Choose Your<br/>Payment Plan</h2></div><p>COURSE VALUE<br/><s>RM3,800</s></p></div><div className="priceGrid"><article className="price reveal"><span>PLAN 01</span><h3>标准付款</h3><div className="amount">RM3,800</div><ul><li>报名时支付 <b>RM380</b></li><li>开课前一星期 <b>RM3,420</b></li><li>一次完成课程费用</li></ul><button onClick={()=>open("Standard Payment")}>选择标准付款 ↗</button></article><article className="price reveal"><span>PLAN 02</span><h3>分期付款</h3><div className="amount">RM380 <small>报名费</small></div><div className="install">+ RM900 × 4 期</div><ul><li>总付款 <b>RM3,980</b></li><li>降低一次性付款压力</li><li>按月完成课程费用</li></ul><button onClick={()=>open("Instalment Payment")}>选择分期付款 ↗</button></article><article className="price featured reveal"><div className="best">BEST VALUE</div><span>PLAN 03 / RYANKEY FANS</span><h3>粉丝专属优惠</h3><s>RM3,800</s><div className="amount">RM3,040</div><div className="save">SAVE RM760 / 20% OFF</div><ul><li>一次性全额付款</li><li>只限关注 RyanKey 的粉丝</li><li>全课程最佳优惠</li></ul><button onClick={()=>open("RyanKey Fans Special")}>领取粉丝优惠 ↗</button></article></div></section>
<section className="faq section" id="faq"><p className="label">06 / FAQ</p><div className="faqGrid"><h2>你可能<br/>想问。</h2><div>{faqs.map((f,i)=><details key={f[0]}><summary><span>0{i+1}</span>{f[0]}<b>＋</b></summary><p>{f[1]}</p></details>)}</div></div></section>
<section className="finalCta"><p>2026 / THE NEXT CHAPTER</p><h2>不要只学习<br/>如何做网站。</h2><h3>学习如何用 AI<br/>把你的能力变成事业。</h3><div><p>DON&apos;T JUST LEARN TO BUILD WEBSITES.<br/>LEARN TO BUILD YOUR FUTURE WITH AI.</p><button onClick={()=>open()}>JOIN FREELANCER COURSE 2026 ↗</button></div></section></main>
<footer><div className="footerBrand">2026<br/>FREELANCER<br/>COURSE</div><div><b>AI WEBSITE DEVELOPMENT<br/>× FREELANCER SKILLS</b><p>RyanKey Designs</p></div><div className="social"><a href="https://ryankey.com.my" target="_blank">Website ↗</a><a href="https://facebook.com/ryankeydesigns" target="_blank">Facebook ↗</a><a href="https://instagram.com/ryankeydesigns" target="_blank">Instagram ↗</a><a href="https://youtube.com" target="_blank">YouTube ↗</a><a href="https://wa.me/60127740280" target="_blank">WhatsApp ↗</a></div><small>© Copyright 2026 RyanKey Designs — All Rights Reserved.</small></footer>
{modal&&<div className="modalBack" role="dialog" aria-modal="true" onMouseDown={e=>e.target===e.currentTarget&&setModal(false)}><div className="modal"><button className="close" onClick={()=>setModal(false)} aria-label="关闭">×</button>{sent?<div className="success"><span>✓</span><h2>报名资料已收到</h2><p>WhatsApp 正在打开。我们将通过 WhatsApp 与您联系。</p><button onClick={()=>setModal(false)}>完成</button></div>:<><p className="label">JOIN / 2026</p><h2>开始你的<br/>Freelancer 旅程。</h2><form onSubmit={submit}><label>姓名 *<input name="name" required placeholder="Your name"/></label><label>WhatsApp 电话 *<input name="phone" required inputMode="tel" pattern="[+0-9 ()-]{9,}" placeholder="+60 12-345 6789"/></label><label>Email *<input name="email" type="email" required placeholder="name@email.com"/></label><label>选择付款方案 *<select name="plan" value={plan} onChange={e=>setPlan(e.target.value as Plan)}><option>Standard Payment</option><option>Instalment Payment</option><option>RyanKey Fans Special</option></select></label><label>目前职业 *<select name="occupation" required><option value="">请选择</option><option>Student</option><option>Freelancer</option><option>Designer</option><option>Business Owner</option><option>Employee</option><option>Others</option></select></label><label className="consent"><input type="checkbox" required/>我同意提交以上资料，并允许课程负责人通过 WhatsApp 或 Email 与我联系。</label>{error&&<p className="error">{error}</p>}<button className="submit" type="submit">提交报名资料 ↗</button></form></>}</div></div>}</>}
